import { parentPort, workerData } from 'worker_threads';
import PDFDocument from 'pdfkit';
import { Buffer } from 'buffer';
import { PassThrough } from 'stream';

async function generatePDF(data) {
  const { trip, currency } = data;
  
  const formatCurrency = (val) => {
    const raw = String(val).replace(/[^\d.-]/g, '');
    const numericVal = parseFloat(raw) || 0;

    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: currency || 'INR',
      maximumFractionDigits: 0
    }).format(numericVal);
  };

  const chunks = [];
  const doc = new PDFDocument({ 
    margin: 50,
    size: 'A4',
    bufferPages: true 
  });

  const stream = doc.pipe(new PassThrough());

  stream.on('data', chunk => chunks.push(chunk));
  stream.on('end', () => {
    const result = Buffer.concat(chunks);
    parentPort.postMessage({ status: 'done', buffer: result });
  });

  stream.on('error', (err) => {
    parentPort.postMessage({ status: 'error', error: err.message });
  });

  try {
    doc.fontSize(28).fillColor('#513b56').text(trip.title?.toUpperCase() || 'WANDERAI ITINERARY', { 
      align: 'center',
      characterSpacing: 2
    });
    
    doc.moveDown();
    doc.fontSize(14).fillColor('#5dd39e').text(trip.destination?.toUpperCase() || '', { align: 'center' });
    doc.moveDown(2);
    
    doc.fontSize(10).fillColor('#525174').text(`GENERATED BY WANDERAI`, { align: 'center', opacity: 0.5 });
    doc.moveDown(4);

    const it = trip.itinerary || {};
    if (it.days && Array.isArray(it.days)) {
      it.days.forEach((day, index) => {
        if (index > 0) doc.addPage();
        
        doc.fontSize(18).fillColor('#513b56').text(`DAY ${index + 1}: ${day.title?.toUpperCase() || ''}`);
        doc.moveDown();
        
        if (day.places && Array.isArray(day.places)) {
          day.places.forEach(p => {
            doc.fontSize(12).fillColor('#5dd39e').text(`${p.name?.toUpperCase()} — ${formatCurrency(p.cost)}`);
            doc.fontSize(10).fillColor('#525174').text(p.description || '');
            doc.moveDown(0.5);
          });
        }
        
        doc.moveDown();
        doc.fontSize(10).fillColor('#348aa7').text(`Day Total: ${formatCurrency(day.dayCost)}`);
        doc.fontSize(10).fillColor('#348aa7').text(`Transport: ${day.transport || 'N/A'}`);
        doc.fontSize(10).fillColor('#348aa7').text(`Accommodation: ${day.accommodation || 'N/A'}`);
      });
    }

    doc.end();
  } catch (err) {
    parentPort.postMessage({ status: 'error', error: `Content generation failed: ${err.message}` });
  }
}

generatePDF(workerData).catch(err => {
  parentPort.postMessage({ status: 'error', error: `Worker fatal error: ${err.message}` });
});
